version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: tuesday
      time: "11:30"
      timezone: Europe/Athens
    reviewers:
      - XhmikosR
    labels:
      - dependencies
    versioning-strategy: increase
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      day: tuesday
      time: "11:30"
      timezone: Europe/Athens
    reviewers:
      - XhmikosR
    labels:
      - dependencies
      - github_actions
